version: "3.6"
services:
  api:
    build: .
    ports:
      - 9007:9007
    expose:
      - 9007
    env_file:
      - .env
  db:
    image: mysql:8-debian
    restart: always
    ports:
      - 3307:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "api"
      MYSQL_USER: "api"
      MYSQL_PASSWORD: "api"
      TELEMETRY_HTTPCLIENT_TLS: "false"
      TELEMETRY_EXPORTER_JAEGER_AGENT_HOST: "localhost"
      TELEMETRY_ENVIRONMENT: local

  adminer:
    image: adminer
    depends_on:
      - db
    restart: always
    ports:
      - 8080:8080
