version: "3.6"
services:
  api:
    build: .
    ports:
      - 9007:9007
    expose:
      - 9007
    env_file:
      - .env.desenv
    extra_hosts:
      - "silo8-master.mysql.bdh.desenv.bb.com.br:170.66.41.165"
      - "canais.fontes.intranet.bb.com.br:170.66.49.75"
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./_data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  # db:
  #   image: mysql:8-debian
  #   restart: always
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - ./data/mysql:/var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: "root"
  #     MYSQL_DATABASE: "api"
  #     MYSQL_USER: "api"
  #     MYSQL_PASSWORD: "api"

  # adminer:
  #   image: adminer
  #   depends_on:
  #     - db
  #   restart: always
  #   ports:
  #     - 8080:8080

  
